plugins:
  - stylelint-scss
extends:
  - stylelint-config-standard-scss
  - stylelint-config-recess-order
  - stylelint-config-prettier-scss
rules:
  alpha-value-notation: number
  at-rule-name-space-after: always
  comment-empty-line-before:
    - always
    - except:
      - first-nested
    - ignore:
      - after-comments
      - stylelint-commands
  custom-media-pattern: null
  custom-property-pattern: null
  font-family-no-missing-generic-family-keyword: null
  function-url-quotes: always
  keyframes-name-pattern: null
  max-empty-lines:
    - 2
    - ignore:
      - comments
  no-descending-specificity: null
  number-leading-zero: never
  number-max-precision:
    - 4
    - ignoreUnits:
      - em
      - rem
      - '%'
      - vw
      - vh
      - vmax
      - vmin
  property-no-vendor-prefix: null
  selector-attribute-operator-space-after: always
  selector-attribute-operator-space-before: always
  selector-class-pattern: null
  selector-id-pattern: null
  selector-no-vendor-prefix: null
  selector-type-no-unknown: null
  scss/at-mixin-argumentless-call-parentheses: always
  scss/comment-no-empty: null
  scss/double-slash-comment-empty-line-before: null
  # scss/double-slash-comment-empty-line-before:
  #   - always
  #   - except:
  #     - first-nested
  #   - ignore:
  #     - between-comments
  #     - stylelint-commands
  #     - inside-block
